// Generated by sim/tools/import_boss_layouts.py from native special rooms.
pub const LAYOUTS:&[(u32,&[i32],[bool;4])]=&[
(1010,&[],[true, true, true, true]),
(1012,&[16, 17, 27, 28, 31, 43, 91, 103, 106, 107, 117, 118],[true, true, true, true]),
(1037,&[16, 17, 18, 19, 20, 31, 32, 33, 34, 46, 47, 48, 61, 62, 63, 76, 77, 78, 91, 92, 93, 94, 106, 107, 108, 109, 110],[false, true, true, true]),
(1038,&[16, 17, 20, 24, 27, 28, 31, 43, 76, 77, 87, 88, 91, 92, 93, 101, 102, 103, 106, 107, 108, 109, 115, 116, 117, 118],[true, false, true, true]),
];
