"""Extract real Monstro rock layouts; RoomEditor/rooms.txt is only a type enum."""
import json,xml.etree.ElementTree as ET
from pathlib import Path
root=Path(__file__).resolve().parents[1]
source=root.parent.parent/'analysis/resources/repentance-a/derived/abp_named_rooms_xml/00.special rooms.xml'
out=[]
for r in ET.parse(source).getroot():
 if r.get('type')!='5' or r.get('variant') not in ('1010','1012','1037','1038'):continue
 rocks=[]
 for s in r.findall('spawn'):
  for e in s.findall('entity'):
   if e.get('type')=='1000':rocks.append((int(s.get('y'))+1)*15+int(s.get('x'))+1)
   else:assert e.get('type')=='20',e.attrib
 doors=[False]*4
 for d in r.findall('door'):
  if d.get('exists')=='True':doors[0 if d.get('x')=='-1' else 2 if d.get('x')=='13' else 1 if d.get('y')=='-1' else 3]=True
 out.append(dict(variant=int(r.get('variant')),name=r.get('name'),rocks=rocks,doors=doors))
target=root/'src/layouts.rs'
target.write_text('// Generated by sim/tools/import_boss_layouts.py from native special rooms.\n'+'pub const LAYOUTS:&[(u32,&[i32],[bool;4])]=&[\n'+''.join(f'({r["variant"]},&{r["rocks"]},{str(r["doors"]).lower()}),\n' for r in out)+'];\n',encoding='utf8')
(root/'tests/fixtures/monstro_layouts.json').write_text(json.dumps(dict(source=str(source.relative_to(root.parent.parent)),rooms=out),indent=2),encoding='utf8')
print([(r['variant'],len(r['rocks']),r['doors']) for r in out])
